apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app
  namespace: dev
spec:
  replicas: 2
  selector:
    app: my-app
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
    spec:
     containers:
        - name: my-app    
          image: nginx
          ports:
              - containerPort: 80
~                                                