apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
    - containerPort: 80
      protocol: TCP
  - name: myapp-container2
    image: tomcat
    ports:
    - containerPort: 8080
      protocol: TCP
  - name: myapp-container3
    image: http
    ports:
    - containerPort: 80
      protocol: TCP