
apiVersion: v1
kind: Service
metadata:
  name: myapp1
spec:
  selector:
  name: myapp2
ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80

  - protocol: TCP
    name: java
    port: 8080
    targetPort: 8080